- hosts: all
  connection: local
  gather_facts: False
  tasks:
    #- debug: var=hostvars[inventory_hostname]
    - debug: msg="{{ inventory_hostname + ' ' + ansible_ssh_host + ' ' + vmware_uuid }}"


