- hosts: all
  user: root
  gather_facts: False
  tasks:

    - debug: msg="{{ inventory_hostname + ' ' + ansible_ssh_host }}"

    - name: install epel
      yum: name=epel-release state=present

    - name: install docker
      yum: name=docker state=latest


