- name: set basic configuration on newly created guests
  hosts: all
  user: root
  gather_facts: False
  tasks:

    - debug: var=hostvars

    - name: show host information
      debug: msg="{{ inventory_hostname + ' ' + ansible_ssh_host }}"

    - name: wait for ssh to respond
      local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started delay=10

    - name: install libselinux
      yum: name=libselinux-python state=present

    - name: install epel
      yum: name=epel-release state=present

    - name: install libselinux
      yum: name=libselinux-python state=present

    - name: set the hostname to match the guest name
      #hostname: name="{{ inventory_hostname }}"
      hostname_set: name="{{ inventory_hostname }}"
      register: hostcheck

    #- name: undo the ansible_hostname change
    #  set_fact:
    #    ansible_hostname: "{{ ansible_ssh_host }}"

    - name: reboot if hostname changed
      reboot:
      when: hostcheck.changed

    #- name: wait for the host to come back online
    #  local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started delay=10
    #  when: hostcheck.changed



