- name: set the hostname and reboot
  hosts: all
  user: root
  gather_facts: False
  tasks:

    - name: show host information
      debug: msg="{{ inventory_hostname + ' ' + ansible_ssh_host }}"

    - name: install libselinux
      yum: name=libselinux-python state=present

    - name: install epel
      yum: name=epel-release state=present

    - name: install libselinux
      yum: name=libselinux-python state=present

    - name: set the hostname to match the guest name
      hostname: name="{{ inventory_hostname }}"
      register: hostcheck

    - name: reboot if hostname changed
      shell: shutdown -r now
      async: 0
      poll: 0
      when: hostcheck.changed

    - name: wait for the host to come back online
      local_action: wait_for host={{ inventory_hostname }} state=started
      when: hostcheck.changed



